In [3]:
import numpy as np

data = [15,16,18,19,22,24,29,30,34]

print("mean : ", np.mean(data))
print ("median : ", np.median(data))
print("50th percentile :", np.percentile(data, 50))
print ("25th percentile: ", np.percentile(data, 25))
print("standard deviation : ", np.std(data))
print("variance : ", np.var(data))

mean :  23.0
median :  22.0
50th percentile : 22.0
25th percentile:  18.0
standard deviation :  6.342099196813483
variance :  40.22222222222222


In [4]:
import pandas as pd

df = pd.read_csv('/home/lakkuga/Desktop/titanic.csv')
print(df.head())

   Survived   Pclass     Sex  Age  Siblings/Spouses  Parents/Children     Fare
0          0       3    male   22                 1                 0   7.2500
1          1       1  female   38                 1                 0  71.2833
2          1       3  female   26                 0                 0   7.9250
3          1       1  female   35                 1                 0  53.1000


In [9]:
import pandas as pd

#pd.options.display.max_columns = 6
df = pd.read_csv('/home/lakkuga/Desktop/titanic.csv')
#print(df.describe())
col = df['Fare']
print(col)


0     7.2500
1    71.2833
2     7.9250
3    53.1000
Name: Fare, dtype: float64


In [19]:
import pandas as pd

df = pd.read_csv('/home/lakkuga/Desktop/titanic.csv')
small_df = df[['Age', 'Sex', 'Survived ']]
print(small_df.head())

   Age     Sex  Survived 
0   22    male          0
1   38  female          1
2   26  female          1
3   35  female          1


In [2]:
import pandas as pd
df = pd.read_csv( '/home/lakkuga/Desktop/titanic.csv')
df['male'] = df['Sex'] == 'male'
print(df.head())

   Survived   Pclass     Sex  Age  Siblings/Spouses  Parents/Children  \
0          0       3    male   22                 1                 0   
1          1       1  female   38                 1                 0   
2          1       3  female   26                 0                 0   
3          1       1  female   35                 1                 0   

      Fare   male  
0   7.2500   True  
1  71.2833  False  
2   7.9250  False  
3  53.1000  False  


In [3]:
import pandas as pd
df = pd.read_csv('/home/lakkuga/Desktop/titanic.csv')
print(df['Fare'].values)

[ 7.25   71.2833  7.925  53.1   ]


In [10]:
import pandas as pd
df = pd.read_csv('/home/lakkuga/Desktop/titanic.csv')
print(df[['Pclass', 'Fare', 'Age']].values)

[[ 3.      7.25   22.    ]
 [ 1.     71.2833 38.    ]
 [ 3.      7.925  26.    ]
 [ 1.     53.1    35.    ]]


In [15]:
import pandas as pd
df = pd.read_csv('/home/lakkuga/Desktop/titanic.csv')
arr = df[['Pclass', 'Fare', 'Age']].values
print(arr.shape)

(4, 3)


In [11]:
import pandas as pd
df = pd.read_csv('/home/lakkuga/Desktop/titanic.csv')
arr = df[['Pclass', 'Fare', 'Age']].values
print(arr[0,0])
print(arr[0]) #single row
print(arr[:,1]) #single column

3.0
[ 3.    7.25 22.  ]
[ 7.25   71.2833  7.925  53.1   ]


In [12]:
import pandas as pd
df = pd.read_csv('/home/lakkuga/Desktop/titanic.csv')
arr = df[['Pclass', 'Fare', 'Age']].values[:10] #take first 10 values for simplicity
mask = arr[:, 1] < 50
#print(arr[mask])
print(arr[arr[:, 1]<50])

[[ 3.     7.25  22.   ]
 [ 3.     7.925 26.   ]]


In [13]:
import pandas as pd
df = pd.read_csv('/home/lakkuga/Desktop/titanic.csv')
arr = df[['Pclass', 'Fare', 'Age']].values
print((arr[:,1]<50).sum())

2


In [30]:
import pandas as pd
df = pd.read_csv('/home/lakkuga/Desktop/titanic1.csv')
list(df.columns.values)
#print(df)
#creating a boolean column for Sex
df['male'] = df['Sex'] == 'male'
X = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
y = df['Survived'].values

print(X)
print(y)

[[3 True 22.0 1 0 7.25]
 [1 False 38.0 1 0 71.2833]
 [3 False 26.0 0 0 7.925]
 ...
 [3 False 7.0 1 2 23.45]
 [1 True 26.0 0 0 30.0]
 [3 True 32.0 0 0 7.75]]
[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1
 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0 0
 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0
 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0 0
 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1 1
 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0
 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0 0 1
 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1 1 0
 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0
 0 0 0 1 0 1 0 1 1

In [33]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt

df = pd.read_csv('/home/lakkuga/Desktop/titanic1.csv')
X = df[['Fare', 'Age']].values
y = df['Survived'].values

model = LogisticRegression()
print(model.fit(X,y))
#plt.scatter(df['Fare'], df['Age'], c=df['Survived'])
#plt.xlabel('Fare')
#plt.ylabel('Age')
print(model.coef_, model.intercept_)




LogisticRegression()
[[ 0.01615949 -0.01549065]] [-0.51037152]


In [35]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
df = pd.read_csv('/home/lakkuga/Desktop/titanic1.csv')
df['male'] = df['Sex'] == 'male'
X = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
y = df['Survived'].values
model = LogisticRegression()
model.fit(X, y)
print(model.predict([[3, True, 22.0, 1, 0, 7.25]]))
print(model.predict(X[:5]))
print(y[:5])

[0]
[0 1 1 1 0]
[0 1 1 1 0]


In [38]:
import pandas as pd 
from sklearn.linear_model import LogisticRegression
df = pd.read_csv('/home/lakkuga/Desktop/titanic1.csv')
df['male'] = df['Sex'] == 'male'
X = df[['Pclass', 'male', 'Age', 'Siblings/Spouses', 'Parents/Children', 'Fare']].values
y = df['Survived'].values

model = LogisticRegression()
model.fit(X, y)

y_pred = model.predict(X)
print((y == y_pred).sum())
print((y == y_pred).sum() / y.shape[0])

print(model.score(X,y))


714
0.8049605411499436
0.8049605411499436


In [40]:
from sklearn.datasets import load_breast_cancer
cancer_data = load_breast_cancer()
print(cancer_data.keys())
print(cancer_data['DESCR'])

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])
.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were c

In [45]:
import pandas as pd
from sklearn.datasets import load_breast_cancer

cancer_data =  load_breast_cancer()
#column names
print(cancer_data['feature_names'])
#print column values
print(cancer_data['data'])
df = pd.DataFrame(cancer_data['data'], columns = cancer_data['feature_names'])
df['target'] = cancer_data['target']
print(df.head())

['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
   mean radius  mean texture  mean pe

In [51]:
import pandas as pd
from sklearn.datasets import load_breast_cancer

cancer_data = load_breast_cancer()
df = pd.DataFrame(cancer_data['data'], columns = cancer_data['feature_names'])
df['target'] = cancer_data['target']

X = df[cancer_data.feature_names].values
y = df['target'].values

#Now we create a Logistic Regression object and use the fit method to build the model.

model = LogisticRegression(solver = 'liblinear')
model.fit(X, y)
print(model.predict(X[:5]))
print(model.score(X, y))

[0 0 0 1 0]
0.9595782073813708
